{{ if .Values.ca_bundle.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.ca_bundle.request_ca_bundle }}: |-
{{ .Files.Get .Values.ca_bundle.request_ca_bundle | indent 4 }}
  {{ .Values.ca_bundle.aws_ca_bundle }}: |-
{{ .Files.Get .Values.ca_bundle.aws_ca_bundle | indent 4 }}
{{ end -}}